name: Generate Documentation

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "typedoc.json"
      - "docs-assets/**"
      - ".github/workflows/docs.yml"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install documentation tools
        run: |
          # Instalovat s příznakem --legacy-peer-deps pro obejití kontroly kompatibility
          npm install --save-dev typedoc@0.25.13 typedoc-plugin-markdown@3.17.1 --legacy-peer-deps || true
          # Ujistit se, že existuje složka docs-assets
          mkdir -p docs-assets

      - name: Generate documentation
        run: npm run docs || echo "Documentation generation failed but continuing"

      - name: Ensure docs directory exists
        run: |
          # Vytvořit prázdný docs adresář, pokud neexistuje
          mkdir -p docs
          # Vytvořit základní index.html, pokud neexistuje
          if [ ! -f docs/index.html ]; then
            echo "<html><body><h1>Firestore Helper TS</h1><p>API Documentation will be available soon.</p></body></html>" > docs/index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
